Trunk/OrchardCms/Orchard/Orchard.Web/Modules/Orchard.Comments/Controllers/CommentController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Orchard.Comments.Models;
using Orchard.Comments.Services;
using Orchard.Comments.ViewModels;
using Orchard.ContentManagement;
using Orchard.Localization;
using Orchard.Mvc.Extensions;
using Orchard.UI.Notify;

namespace Orchard.Comments.Controllers {
    public class CommentController : Controller {
        public IOrchardServices Services { get; set; }
        private readonly ICommentService _commentService;
        private readonly INotifier _notifier;

        public CommentController(IOrchardServices services, ICommentService commentService, INotifier notifier) {
            Services = services;
            _commentService = commentService;
            _notifier = notifier;
            T = NullLocalizer.Instance;
        }

        public Localizer T { get; set; }

        [HttpPost, ValidateInput(false)]
        public ActionResult Create(string returnUrl) {
            if (!Services.Authorizer.Authorize(Permissions.AddComment, T("Couldn't add comment")))
                return this.RedirectLocal(returnUrl, "~/");
            
            var viewModel = new CommentsCreateViewModel();

            TryUpdateModel(viewModel);
            
            var context = new CreateCommentContext {
                Author = viewModel.Name,
                CommentText = viewModel.CommentText,
                Email = viewModel.Email,
                SiteName = viewModel.SiteName,
                CommentedOn = viewModel.CommentedOn
            };


            if (ModelState.IsValid) {
                if (!String.IsNullOrEmpty(context.SiteName) && !context.SiteName.StartsWith("http://") && !context.SiteName.StartsWith("https://")) {
                    context.SiteName = "http://" + context.SiteName;
                }

                CommentPart commentPart = _commentService.CreateComment(context, Services.WorkContext.CurrentSite.As<CommentSettingsPart>().Record.ModerateComments);

                if (commentPart.Record.Status == CommentStatus.Pending) {
                    // if the user who submitted the comment has the right to moderate, don't make this comment moderated
                    if (Services.Authorizer.Authorize(Permissions.ManageComments)) {
                        commentPart.Record.Status = CommentStatus.Approved;
                    }
                    else {
                        Services.Notifier.Information(T("Your comment will appear after the site administrator approves it."));
                    }
                }
            }
            else {
                foreach (var error in ModelState.Values.SelectMany(m => m.Errors).Select( e=> e.ErrorMessage)) {
                    _notifier.Error(T(error));
                }
            }

            if(!ModelState.IsValid) {
                TempData["CreateCommentContext.Name"] = context.Author;
                TempData["CreateCommentContext.CommentText"] = context.CommentText;
                TempData["CreateCommentContext.Email"] = context.Email;
                TempData["CreateCommentContext.SiteName"] = context.SiteName;
            }

            return this.RedirectLocal(returnUrl, "~/");
        }
    }
}

Trunk/OrchardCms/Orchard/Orchard.Web/Modules/Orchard.Comments/Views/CommentAuthor.cshtml
@*
    Model:
      ContentPart
*@

@using Orchard.Comments.Models;
@using Orchard.Utility.Extensions;

@{
    var comment = (Orchard.Comments.Models.CommentPart)Model.ContentPart;
}

@Html.LinkOrDefault(comment.Record.Author, comment.Record.SiteName, new { rel = "nofollow" })

Trunk/OrchardCms/Orchard/Orchard.Web/Modules/Orchard.Comments/Views/CommentMetadata.cshtml
@*
    Model:
      ContentPart
*@

@using Orchard.Comments.Models;
@using Orchard.Utility.Extensions;
@{
    var comment = (Orchard.Comments.Models.CommentPart)Model.ContentPart;
}

@T("said") <time datetime="@comment.Record.CommentDateUtc.GetValueOrDefault()">@Html.Link((string)Display.DateTimeRelative(dateTimeUtc: comment.Record.CommentDateUtc.GetValueOrDefault()).ToString(), "#comment-" + comment.Id)</time>

Trunk/OrchardCms/Orchard/Orchard.Web/Modules/Orchard.Comments/Views/ListOfComments.cshtml
@model IEnumerable<Orchard.Comments.Models.CommentPart>
@using Orchard.Comments.Models;
@using Orchard.Utility.Extensions;
<ul class="comments">
@foreach (var comment in Model) {
    <li>
        <article class="comment" id="comment-@comment.Id">
            <header>
                <h4>
                    <span class="who">@Display.CommentAuthor(ContentPart: comment)</span>
                    <span class="when">@Display.CommentMetadata(ContentPart: comment)</span>
                </h4>
            </header>
            <p class="text">@(new MvcHtmlString(Html.Encode(comment.Record.CommentText).ReplaceNewLinesWith("<br />$1")))</p>
        </article>
    </li>
}
</ul>


Trunk/OrchardCms/Orchard/Orchard.Web/Modules/Orchard.Comments/Views/Parts.Comments.Count.SummaryAdmin.cshtml
<ul class="pageStatus">
<li>
    @Display.CommentSummaryLinks(item: Model.ContentPart.ContentItem, count: Model.CommentCount, pendingCount: Model.PendingCount)
    @T(" | ")&nbsp;
</li>
</ul>

Trunk/OrchardCms/Orchard/Orchard.Web/Modules/Orchard.Comments/Views/Parts.Comments.Count.cshtml
@using Orchard.Comments.ViewModels;
<span class="commentcount">@T.Plural("1 Comment", "{0} Comments", (int)Model.CommentCount)</span>

Trunk/OrchardCms/Orchard/Orchard.Web/Modules/Orchard.Comments/Views/Parts.Comments.cshtml
@using Orchard.Comments.Models;
@using Orchard.Comments;
@using Orchard.Security;
@using Orchard.Utility.Extensions;

@{
    var contextExists = TempData["CreateCommentContext.Name"] != null;
    var name = Convert.ToString(TempData["CreateCommentContext.Name"]);
    var commentText = Convert.ToString(TempData["CreateCommentContext.CommentText"]);
    var email = Convert.ToString(TempData["CreateCommentContext.Email"]);
    var siteName = Convert.ToString(TempData["CreateCommentContext.SiteName"]);
}

@if (Model.ContentPart.Comments.Count > 0) {
<div id="comments">
    <h2 class="comment-count">@T.Plural("1 Comment", "{0} Comments", (int)Model.ContentPart.Comments.Count)</h2>
    @{Html.RenderPartial("ListOfComments", (IEnumerable<Orchard.Comments.Models.CommentPart>)Model.ContentPart.Comments);}
</div>
}

@if (Model.ContentPart.CommentsActive == false) {
    if (Model.ContentPart.Comments.Count > 0) {
        <div id="comments">
            <p class="comment-disabled">@T("Comments have been disabled for this content.")</p>
        </div>
    }
}
else if (WorkContext.CurrentUser == null && !AuthorizedFor(Permissions.AddComment)) {
<h2 id="add-comment">@T("Add a Comment")</h2>
<p class="info message">@T("You must {0} to comment.", Html.ActionLink(T("log on").ToString(), "LogOn", new { Controller = "Account", Area = "Orchard.Users", ReturnUrl = string.Format("{0}#addacomment", Context.Request.RawUrl) }))</p>
} else {
using (Html.BeginForm("Create", "Comment", new { area = "Orchard.Comments" }, FormMethod.Post, new { @class = "comment-form" })) { 
    @Html.ValidationSummary() 
    if (WorkContext.CurrentUser == null) {

    <fieldset class="who">
        <legend id="add-comment">@T("Add a Comment")</legend> 
    <ol>
        <li>
            <label for="Name">@T("Name")</label>
            <input id="Name" class="text" name="Name" type="text" value="@(contextExists ? name : String.Empty)" />
        </li>
        <li>
            <label for="Email">@T("Email")</label>
            <input id="Email" class="text" name="Email" type="text" value="@(contextExists ? email : String.Empty)"/>
        </li>
        <li>
            <label for="SiteName">@T("Url")</label>
            <input id="SiteName" class="text" name="SiteName" type="text" value="@(contextExists ? siteName : String.Empty)"/>
        </li>
     </ol>
    </fieldset>
    } else {
        @Html.Hidden("Name", WorkContext.CurrentUser.UserName ?? "")
        @Html.Hidden("Email", WorkContext.CurrentUser.Email ?? "")
    }

    <h2 id="commenter">@if (WorkContext.CurrentUser != null) { @T("Hi, {0}!", WorkContext.CurrentUser.UserName)}</h2>
    <fieldset class="what">
    <ol>
        <li>
            <label for="comment-text">@T("Comment")</label>
            <textarea id="comment-text" rows="10" cols="30" name="CommentText">@(contextExists ? commentText : String.Empty)</textarea>
        </li>
        <li>
            <button class="primaryAction" type="submit">@T("Submit Comment")</button>
            @Html.Hidden("CommentedOn", (int)Model.ContentPart.ContentItem.Id) 
            @Html.Hidden("ReturnUrl", Context.Request.ToUrlString()) 
            @Html.AntiForgeryTokenOrchard() 
        </li>
    </ol>
    </fieldset>
    }
} 